# action.yml
name: 'Jenkins trigger job'
description: 'Trigger jenkins job'
inputs:
  jenkins-url:
    description: 'jenkins server url'
    required: true
  jenkins-token:
    description: 'token to access jenkins server'
    required: true
  user:
    description: "user name"
    required: true
  job-name:
    description: '/job/job_name'
    required: true
  job-params:
    description: "params to run the job. JSON string. i.e '{'param1': 'value1', 'param2': 'value2'}' "
    required: false
outputs:
  job_status:
    description: 'Build status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jenkins-url}}
    - ${{ inputs.jenkins-token}}
    - ${{ inputs.user}}
    - ${{ inputs.job-name }}
    - ${{ inputs.job-params}}
branding:
  icon: 'award'
  color: 'yellow'